### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by codemann8** [ZuneDev/ZuneShell.dll#2] opened 2021-12-07 22:50 UTC
Sorry, ik this isn't the best use of GitHub Issues, but I didn't see a way to message any other way.

I'm not sure what these repositories here do or how to use/install them. I think I saw a post somewhere that mentioned modding using install files from v2.x  My hope was that there would be a way to use the long-sought-after awesome artist metadata Now Playing visualization that existed way back. Is there a way to get this? Are these repos aimed to restore some of these older features, by modding the 4.8 DLLs? If so, is there a guide on how to install this? And are there compiled releases of these DLLs?

**Comment by yoshiask** [comment] 2021-12-08 00:05
Howdy! I'll try and address your questions individually.

The original purpose of this repository was just to make the cleaned up decompilations of the Zune-related libraries publicly accessible. I wanted to allow other developers to use it in their own projects, particularly UIX, since it's a pretty powerful UI framework. The problem is that the original library has some code to prevent it from being used by non-MS apps, so I patched it out.

Since then, this repo houses source code for 'augmented' versions of the originals, but not quite modded. The plan is to keep the core functionality of these libraries the same as the originals, but still make them more useful (e.g. UIX decompiler, custom debugging protocol, etc.). There won't be any changes made to the code in this repo that a typical user would notice (unless they install external software that uses the added features).
That being said, these augmented libraries might be released as drop-in replacement DLLs, and UIX might even be put on NuGet, but I don't feel there have been enough significant changes to warrant that yet. When the time comes, the recommended way to install these augmentations will be to use the Zune Modding Helper.

Regarding artist metadata and other web services, this repo doesn't have much to do with it. If you're interested in setting up the web services recreations, you can use the [Zune Modding Helper](https://github.com/ZuneDev/ZuneModdingHelper) to install a patch that changes which servers Zune tries to get data from.
> Sadly, `zunes.tk` is offline now and has been replaced by `zunes.me`, and I haven't had time to get the servers running on the new domain. If you really want marketplace stuff now, you'll have to get the various [Python-based servers](https://github.com/orgs/ZuneDev/teams/api/repositories) running on your own machine. Sorry :(

I think I should also note that most everything in the ZuneDev organization is *only* for the desktop software, not the firmware that runs on Zune devices. I hope this answers some of your questions!

**Closed as completed** 2023-04-07 03:11 UTC
